<?php /* Smarty version 2.6.20, created on 2013-03-26 17:38:14
         compiled from header.tpl */

$this->_cache_serials['/home/superchauen/web/negotiablekite/video/Smarty/templates_c/%%F7^F7F^F7F34188%%header.tpl.inc'] = 'a9c15fc0f0dc6962ac99272a401cdd92';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'dropdown_menu_video_categories', 'header.tpl', 262, false),array('function', 'dropdown_menu_article_categories', 'header.tpl', 270, false),)), $this); ?>
<?php
function _smarty_tplfunc_a9c15fc0f0dc6962ac99272a401cdd92_0(&$_smarty)
{
echo smarty_art_html_list_categories(array(), $_smarty);
}



?>
